### ISSUE TITLE
TouchID : Cannot read property 'isSupported' of undefined

### ISSUE THREAD

**Issue by wkwyatt** [naoufal/react-native-touch-id#33]
Here is the code I'm running

`demoTouchID() {
      TouchID.isSupported()
          .then((success) => {
              console.log("TOUCHID WORKS");
          })
          .catch((error) => {
              console.log("TOUCHID ERROR: ", error);
          })
}`

When I tap the button that this function is attached to I get an error saying :

> Cannot read property 'isSupported' of undefined
    at TouchID.ios.js:18
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at Object.isSupported (TouchID.ios.js:17)
    at Object.demoTouchID [as onPress] (BasicAuthApp.js:65)
    at Object.touchableHandlePress (TouchableOpacity.js:125)
    at Object._performSideEffectsForTransition (Touchable.js:742)
    at Object._receiveSignal (Touchable.js:660)
    at Object.touchableHandleResponderRelease (Touchable.js:433)

It also occurs when using .authenticate()

**Comment by GentryRiggen** [comment]
Run the following.

`react-native link`
https://github.com/naoufal/react-native-touch-id#linking-the-library

**Comment by gigeos** [comment]
Open Xcode and check if Header Search Paths and make sure it contains `$(SRCROOT)/../../../react-native/React` as recursive in Build Phase. Solve the problem for me (RN 0.44)

**Comment by klivin** [comment]
I tried running react-native link and adding the header search paths (this should not be necessary if not using anywhere but js code)...

TouchID.isSupported is not a function. (In 'TouchID.isSupported()', 'TouchID.isSupported' is undefined)

Any other ideas?

```
nextStep
    signUp.js:39:8
onPress
    signUp.js:103:61
touchableHandlePress
    TouchableOpacity.js:126:45
_performSideEffectsForTransition
    Touchable.js:746:34
_receiveSignal
    Touchable.js:664:44
touchableHandleResponderRelease
    Touchable.js:433:24
invokeGuardedCallback
    ReactErrorUtils.js:22:15
invokeGuardedCallbackAndCatchFirstError
    ReactErrorUtils.js:133:62
executeDispatch
    EventPluginUtils.js:90:4
executeDispatchesInOrder
    EventPluginUtils.js:121:20
executeDispatchesAndRelease
    EventPluginHub.js:37:46
forEachAccumulated
    forEachAccumulated.js:30:16
processEventQueue
    EventPluginHub.js:233:8
runEventQueueInBatch
    ReactEventEmitterMixin.js:18:35
handleTopLevel
    ReactEventEmitterMixin.js:38:25
<unknown>
    ReactNativeEventEmitter.js:107:8
perform
    Transaction.js:150:24
batchedUpdatesWithControlledComponents
    ReactGenericBatching.js:51:26
_receiveRootNodeIDEvent
    ReactNativeEventEmitter.js:105:40
receiveTouches
    ReactNativeEventEmitter.js:193:8
__callFunction
    MessageQueue.js:250:47
<unknown>
    MessageQueue.js:101:26
__guard
    MessageQueue.js:218:6
callFunctionReturnFlushedQueue
    MessageQueue.js:100:17

```

**Comment by klivin** [comment]
For me it was importing using:

import TouchID from "react-native-touch-id";

did the trick. Needed to be using the es2015 syntax...smh

**Comment by joelcdoyle** [comment]
Having this same issue with `react-native` 0.46.1 and `react-native-touch-id` 3.1.0. 
Running app on Android. None of the above solutions work. 
`react-native link` has no effect.

**Comment by zibs** [comment]
I'm closing this since it seems like @klivin 's issue is solved, and the original author of this issue has never responded.

**Comment by ShortyFR** [comment]
Using version 4.0.0, I still get the same error after linking and using the import syntax.

```
import React from "react"
import TouchID from 'react-native-touch-id'
import { View, TouchableHighlight, Text, Alert } from 'react-native'

type Props = {
  };

const optionalConfigObject = {
  title: "Authentication Required",
  color: "#e00606"
}

export default class TouchId extends React.Component<Props> {

  componentDidMount() {
    TouchID.isSupported()
        .then(supported => {
            console.log('it is supported');
        })
        .catch(err => {
            console.log(err.message);
        })
  }

  _pressHandler() {
    TouchID.authenticate('to demo this react-native component', optionalConfigObject)
      .then(success => {
        Alert.alert('Info', 'Authenticated Successfully');
      })
      .catch(error => {
        Alert.alert('Error', 'Authentication Failed '+error);
      });
  }

  render() {
    return (
      <View>
        <TouchableHighlight onPress={this._pressHandler}>
          <Text>
            Authenticate with Touch ID
          </Text>
        </TouchableHighlight>
      </View>
    );
  }
};
```

I get the error "Cannot read property 'isSupported' of indefined.
And it I press the button, I get "Authentication Failed TypeError: Cannot read property 'authenticate' of undefined".

**Comment by jackychanfox** [comment]
No body solve this problem?

**Comment by jtich** [comment]
Anyone know of a fix for this issue??

**Comment by brandons** [comment]
I'm still receiving this error on Android using version 4.0.4 and everything appears to be linked correctly. 

```TypeError: Cannot read property 'isSupported' of undefined
    at TouchID.android.js:8
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at Object.isSupported (TouchID.android.js:7)
    at SecuritySettingsScreen.syncPreferences (SecuritySettingsScreen.js:137)
    at new SecuritySettingsScreen (SecuritySettingsScreen.js:106)
    at constructClassInstance (ReactNativeRenderer-dev.js:6729)
    at updateClassComponent (ReactNativeRenderer-dev.js:8810)
    at beginWork (ReactNativeRenderer-dev.js:9646)
    at performUnitOfWork (ReactNativeRenderer-dev.js:12361)
    at workLoop (ReactNativeRenderer-dev.js:12384)
    at renderRoot (ReactNativeRenderer-dev.js:12427)
    at performWorkOnRoot (ReactNativeRenderer-dev.js:13034)
    at performWork (ReactNativeRenderer-dev.js:12951)
    at performSyncWork (ReactNativeRenderer-dev.js:12913)
    at requestWork (ReactNativeRenderer-dev.js:12799)
    at scheduleWorkImpl (ReactNativeRenderer-dev.js:12666)
    at scheduleWork (ReactNativeRenderer-dev.js:12622)
    at scheduleRootUpdate (ReactNativeRenderer-dev.js:13324)
    at _updateContainerAtExpirationTime (ReactNativeRenderer-dev.js:13359)
    at Object.updateContainer (ReactNativeRenderer-dev.js:13384)
    at Object.render (ReactNativeRenderer-dev.js:14119)
    at renderApplication (renderApplication.js:58)
    at Object.run (AppRegistry.js:103)
    at Object.runApplication (AppRegistry.js:196)
    at MessageQueue.__callFunction (MessageQueue.js:353)
    at MessageQueue.js:118
    at MessageQueue.__guardSafe (MessageQueue.js:316)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:117)
    at debuggerWorker.js:72
```

**Comment by luciodale** [comment]
I could solve this problem by inspecting the TouchID object and realizing that to call the functions `isSupported()` or `authenticate("foo")` a further key must be accessed:

`TouchID.default.isSupported().then(...)` and `TouchID.default.authenticate("foo").then(...)` 

I have no idea why the `default` key is there, but it works as a temporary workaround..
